fn main() {
    // Register our own IPC commands with the ACL so they can be invoked from
    // the REMOTE origin the main window navigates to in production
    // (http://127.0.0.1:8000, where the FastAPI backend serves the SPA).
    //
    // Tauri 2 auto-allows application commands only for LOCAL (tauri://)
    // content. For a remote URL, each command needs an explicit
    // ``allow-<command>`` permission — autogenerated by ``.commands(...)``
    // below — granted to that origin in ``capabilities/default.json``.
    // Without this, invoking them from the SPA fails at runtime with
    // "command <name> not allowed by acl" (this is why the in-app updater's
    // ``check_for_channel`` was rejected). Plugin commands (updater/opener/…)
    // already worked because their permissions were listed in the capability.
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                "restart_backend",
                "check_for_channel",
                "install_for_channel",
            ]),
        ),
    )
    .expect("failed to run tauri-build");
}
