#!/usr/bin/env bash
# Drevalis Creator Studio installer.
#
#   curl -fsSL https://drevalis.com/install.sh | bash
#
# What this script does:
#   1. Checks Docker + Docker Compose are installed
#   2. Creates /srv/drevalis (or $INSTALL_DIR if set) and enters it
#   3. Writes docker-compose.yml pulling official images from GHCR
#   4. Generates an ENCRYPTION_KEY (Fernet) and writes .env
#   5. Pulls images and brings up the stack
#   6. Prints the URL to open + next steps
#
# Re-running the script on an existing install is safe: it won't overwrite
# the .env (your secrets stay) and compose will just pull + restart.
#
# Env vars you can override:
#   INSTALL_DIR            (default: /srv/drevalis)
#   IMAGE_REGISTRY         (default: ghcr.io/drevalis)
#   IMAGE_TAG              (default: stable)
#   LICENSE_SERVER_URL     (default: https://license.drevalis.com)

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/srv/drevalis}"
IMAGE_REGISTRY="${IMAGE_REGISTRY:-ghcr.io/drevaliscs}"
IMAGE_TAG="${IMAGE_TAG:-stable}"
LICENSE_SERVER_URL="${LICENSE_SERVER_URL:-https://license.drevalis.com}"

BOLD=$'\033[1m'; DIM=$'\033[2m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RED=$'\033[31m'; RESET=$'\033[0m'

log()  { printf '%s>%s %s\n'    "$GREEN"  "$RESET" "$*"; }
warn() { printf '%s!%s %s\n'    "$YELLOW" "$RESET" "$*"; }
die()  { printf '%sX%s %s\n' "$RED"    "$RESET" "$*" >&2; exit 1; }

# ??? 1. Prerequisites ?????????????????????????????????????????????????????

command -v docker >/dev/null 2>&1 \
  || die "Docker is not installed. See https://docs.docker.com/engine/install/"

if ! docker compose version >/dev/null 2>&1; then
  die "Docker Compose plugin not installed. On Ubuntu/Debian: apt install docker-compose-plugin"
fi

if ! docker info >/dev/null 2>&1; then
  die "Docker daemon is not running (or your user can't reach the socket). Try: sudo systemctl start docker && sudo usermod -aG docker \$USER (then log out and back in)"
fi

log "Docker ${BOLD}$(docker version --format '{{.Server.Version}}')${RESET} detected"

# ??? 2. Install directory ????????????????????????????????????????????????

if [[ ! -d "$INSTALL_DIR" ]]; then
  log "Creating $INSTALL_DIR"
  if ! mkdir -p "$INSTALL_DIR" 2>/dev/null; then
    log "Needs sudo to create $INSTALL_DIR"
    sudo mkdir -p "$INSTALL_DIR"
    sudo chown -R "$(id -u):$(id -g)" "$INSTALL_DIR"
  fi
fi

cd "$INSTALL_DIR"
log "Working directory: ${BOLD}$(pwd)${RESET}"

# ??? 3. docker-compose.yml ???????????????????????????????????????????????

COMPOSE_FILE="$INSTALL_DIR/docker-compose.yml"
log "Writing $COMPOSE_FILE"

cat > "$COMPOSE_FILE" <<COMPOSE_EOF
# Drevalis Creator Studio -- generated by install.sh
# Image tag: $IMAGE_TAG
# Regenerate: rerun curl -fsSL https://drevalis.com/install.sh | bash

# Pin the project name so docker compose on the host and the updater
# sidecar (which runs compose from /project inside the container) both
# target the same stack. Without this, in-app updates silently create a
# parallel "project" stack instead of restarting the real one.
name: drevalis

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: drevalis
      POSTGRES_PASSWORD: drevalis
      POSTGRES_DB: drevalis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U drevalis"]
      interval: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 20

  app:
    image: $IMAGE_REGISTRY/creator-studio-app:$IMAGE_TAG
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DATABASE_URL: postgresql+asyncpg://drevalis:drevalis@postgres:5432/drevalis
      REDIS_URL: redis://redis:6379/0
      PYTHONPATH: /app/src
    volumes:
      - ./storage:/app/storage
      - updater_shared:/shared
    working_dir: /app
    # Run migrations inline before uvicorn. Previous setup used a separate
    # migrate one-shot with depends_on.service_completed_successfully, but
    # that deadlocked the stack (502 on every endpoint) when the one-shot
    # failed for any reason. Inline is more robust and surfaces alembic
    # errors in the same log stream the operator is already watching.
    # Absolute paths -- PATH inheritance is unreliable across compose
    # string-commands vs exec-form. See install.ps1 for the full note.
    command: sh -c "/app/.venv/bin/python -m alembic upgrade head && exec /app/.venv/bin/python -m uvicorn drevalis.main:app --host 0.0.0.0 --port 8000 --workers 4"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    depends_on:
      postgres: { condition: service_healthy }
      redis:    { condition: service_healthy }

  worker:
    # Same image as ``app``; only the startup command differs.
    image: $IMAGE_REGISTRY/creator-studio-app:$IMAGE_TAG
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: postgresql+asyncpg://drevalis:drevalis@postgres:5432/drevalis
      REDIS_URL: redis://redis:6379/0
      PYTHONPATH: /app/src
    volumes:
      - ./storage:/app/storage
    command: python -m arq drevalis.workers.settings.WorkerSettings
    depends_on:
      postgres: { condition: service_healthy }
      redis:    { condition: service_healthy }
      app:      { condition: service_healthy }

  frontend:
    image: $IMAGE_REGISTRY/creator-studio-frontend:$IMAGE_TAG
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - app

  updater:
    image: $IMAGE_REGISTRY/creator-studio-updater:$IMAGE_TAG
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/project
      - updater_shared:/shared
    environment:
      POLL_SECONDS: "15"
      # Force the sidecar's docker compose invocations onto the real
      # stack (see top-level \`name:\` -- kept in sync here for safety).
      COMPOSE_PROJECT_NAME: "drevalis"

volumes:
  postgres_data:
  updater_shared:
COMPOSE_EOF

# ??? 4. .env ????????????????????????????????????????????????????????????

ENV_FILE="$INSTALL_DIR/.env"
if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists -- keeping your existing values"
else
  log "Generating encryption key"
  ENC_KEY=$(docker run --rm python:3.11-slim python -c \
    "from cryptography.fernet import Fernet; import subprocess; subprocess.run(['pip','install','-q','cryptography']); from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null \
    || docker run --rm python:3.11-slim bash -c "pip install -q cryptography && python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())'")

  cat > "$ENV_FILE" <<ENV_EOF
# Drevalis Creator Studio -- generated $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# Keep this file private. It stays on your machine; secrets are never sent
# off-box. Back it up if you want to restore your install cleanly.

# Fernet encryption key (encrypts API keys and OAuth tokens at rest).
# NEVER regenerate once data exists -- you'll lose access to stored tokens.
ENCRYPTION_KEY=$ENC_KEY

# Where this install phones home for license activation + heartbeats.
# Change only if you're self-hosting the license server.
LICENSE_SERVER_URL=$LICENSE_SERVER_URL

# Optional API auth token. Leave empty for single-user local dev.
# Set a strong random value if you expose the app on a LAN/WAN.
API_AUTH_TOKEN=

# Optional: override defaults below if needed.
# DEBUG=false
# STORAGE_BASE_PATH=./storage
ENV_EOF
  chmod 600 "$ENV_FILE"
  log "Wrote $ENV_FILE (chmod 600)"
fi

# ??? 5. Pull + start ????????????????????????????????????????????????????

log "Pulling images (this can take a few minutes on first run)?"
docker compose pull

log "Starting the stack?"
docker compose up -d

log "Waiting for the app to become healthy?"
for i in $(seq 1 60); do
  if curl -fs http://localhost:8000/health >/dev/null 2>&1; then
    log "App is healthy"
    break
  fi
  sleep 2
  if [[ $i -eq 60 ]]; then
    warn "App didn't answer /health within 2 minutes -- check 'docker compose logs app'"
  fi
done

# ??? 6. Done ????????????????????????????????????????????????????????????

echo
printf '%s==============================================================%s\n' "$GREEN" "$RESET"
printf '  %sDrevalis Creator Studio is installed%s\n' "$BOLD" "$RESET"
printf '%s==============================================================%s\n' "$GREEN" "$RESET"
echo
echo "  Open:          http://localhost:3000"
echo "  Backend API:   http://localhost:8000/docs"
echo "  Compose dir:   $INSTALL_DIR"
echo
echo "  Next steps:"
echo "   1. Open http://localhost:3000 in your browser"
echo "   2. Paste your license key from the welcome email into the activation screen"
echo "   3. Settings -> ComfyUI Servers -> add your local ComfyUI URL"
echo "   4. Settings -> LLM Configs -> add your LLM endpoint"
echo
echo "  Updates:       inside the app, Settings -> Updates -> 'Update now'"
echo "  Support:       https://drevalis.com/download - support@drevalis.com"
echo
