"""baseline desktop sqlite schema

Revision ID: 6bf6d3143c4c
Revises:
Create Date: 2026-05-08 20:38:04.903840

⚠ FROZEN — DO NOT EDIT ⚠

This file was last modified during early alpha and is now treated as
append-only history. Editing it after a release has shipped causes
schema drift: alembic sees ``alembic_version = '6bf6d3143c4c'`` on
existing installs, declares "already at head", and skips the new
tables you added — yielding ``sqlite3.OperationalError: no such
table: <whatever>`` once the API starts querying.

If you need a new table or column, create a NEW migration with::

    uv run alembic revision -m "add foo table"

then write the upgrade/downgrade ops there. The launcher's
schema-heal (``__main__.py:_run_migrations_inproc``) is a safety net
for the damage already done; it is NOT a substitute for proper
append-only migrations.

See ``GOTCHAS.md`` → "Migrations are append-only".
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import drevalis.models._types


# revision identifiers, used by Alembic.
revision: str = '6bf6d3143c4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_store',
    sa.Column('key_name', sa.TEXT(), nullable=False),
    sa.Column('encrypted_value', sa.TEXT(), nullable=False),
    sa.Column('key_version', sa.INTEGER(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_key_store')),
    sa.UniqueConstraint('key_name', name=op.f('uq_api_key_store_key_name'))
    )
    op.create_table('character_packs',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('thumbnail_asset_id', sa.Uuid(), nullable=True),
    sa.Column('character_lock', sa.JSON(), nullable=True),
    sa.Column('style_lock', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_packs'))
    )
    op.create_table('comfyui_servers',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('api_key_encrypted', sa.TEXT(), nullable=True),
    sa.Column('api_key_version', sa.INTEGER(), server_default='1', nullable=False),
    sa.Column('max_concurrent', sa.INTEGER(), server_default='2', nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('max_concurrent_video_jobs', sa.INTEGER(), nullable=True),
    sa.Column('last_tested_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_test_status', sa.TEXT(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comfyui_servers')),
    sa.UniqueConstraint('name', name=op.f('uq_comfyui_servers_name'))
    )
    op.create_table('comfyui_workflows',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('workflow_json_path', sa.TEXT(), nullable=False),
    sa.Column('version', sa.INTEGER(), server_default='1', nullable=False),
    sa.Column('input_mappings', drevalis.models._types.JSONB(), nullable=False),
    sa.Column('content_format', sa.String(length=20), server_default='any', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comfyui_workflows')),
    sa.UniqueConstraint('name', name=op.f('uq_comfyui_workflows_name'))
    )
    op.create_table('license_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jwt', sa.Text(), nullable=True),
    sa.Column('jwt_key_version', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.String(length=32), nullable=True),
    sa.Column('activated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_heartbeat_status', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_license_state'))
    )
    op.create_table('llm_configs',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('base_url', sa.TEXT(), nullable=False),
    sa.Column('model_name', sa.TEXT(), nullable=False),
    sa.Column('api_key_encrypted', sa.TEXT(), nullable=True),
    sa.Column('api_key_version', sa.INTEGER(), server_default='1', nullable=False),
    sa.Column('max_tokens', sa.INTEGER(), server_default='4096', nullable=False),
    sa.Column('temperature', sa.NUMERIC(), server_default='0.7', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_configs')),
    sa.UniqueConstraint('name', name=op.f('uq_llm_configs_name'))
    )
    op.create_table('prompt_templates',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('template_type', sa.TEXT(), nullable=False),
    sa.Column('system_prompt', sa.TEXT(), nullable=False),
    sa.Column('user_prompt_template', sa.TEXT(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("template_type IN ('script', 'visual', 'hook', 'hashtag')", name=op.f('ck_prompt_templates_template_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates')),
    sa.UniqueConstraint('name', name=op.f('uq_prompt_templates_name'))
    )
    op.create_table('social_platforms',
    sa.Column('platform', sa.TEXT(), nullable=False),
    sa.Column('account_name', sa.TEXT(), nullable=True),
    sa.Column('account_id', sa.TEXT(), nullable=True),
    sa.Column('access_token_encrypted', sa.TEXT(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.TEXT(), nullable=True),
    sa.Column('token_key_version', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('token_expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('account_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("platform IN ('tiktok', 'instagram', 'x', 'facebook')", name=op.f('ck_social_platforms_platform_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_platforms'))
    )
    op.create_index('ix_social_platforms_platform', 'social_platforms', ['platform'], unique=False)
    op.create_index('ix_social_platforms_platform_account', 'social_platforms', ['platform', 'account_id'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('role', sa.TEXT(), server_default='owner', nullable=False),
    sa.Column('display_name', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('session_version', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('totp_secret_encrypted', sa.TEXT(), nullable=True),
    sa.Column('totp_key_version', sa.INTEGER(), nullable=True),
    sa.Column('totp_confirmed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('totp_recovery_codes_encrypted', sa.TEXT(), nullable=True),
    sa.Column('preferences', drevalis.models._types.JSONB(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'editor', 'viewer')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('voice_profiles',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('provider', sa.TEXT(), nullable=False),
    sa.Column('piper_model_path', sa.TEXT(), nullable=True),
    sa.Column('piper_speaker_id', sa.TEXT(), nullable=True),
    sa.Column('speed', sa.NUMERIC(), server_default='1.0', nullable=False),
    sa.Column('pitch', sa.NUMERIC(), server_default='1.0', nullable=False),
    sa.Column('elevenlabs_voice_id', sa.TEXT(), nullable=True),
    sa.Column('kokoro_voice_name', sa.TEXT(), nullable=True),
    sa.Column('kokoro_model_path', sa.TEXT(), nullable=True),
    sa.Column('edge_voice_id', sa.TEXT(), nullable=True),
    sa.Column('gender', sa.TEXT(), nullable=True),
    sa.Column('language_code', sa.TEXT(), nullable=True),
    sa.Column('sample_audio_path', sa.TEXT(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("provider IN ('piper', 'elevenlabs', 'kokoro', 'edge', 'comfyui_elevenlabs')", name=op.f('ck_voice_profiles_provider_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_profiles')),
    sa.UniqueConstraint('name', name=op.f('uq_voice_profiles_name'))
    )
    op.create_table('youtube_channels',
    sa.Column('channel_id', sa.TEXT(), nullable=False),
    sa.Column('channel_name', sa.TEXT(), nullable=False),
    sa.Column('access_token_encrypted', sa.TEXT(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.TEXT(), nullable=True),
    sa.Column('token_key_version', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('token_expiry', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('upload_days', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('upload_time', sa.TEXT(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_channels')),
    sa.UniqueConstraint('channel_id', name=op.f('uq_youtube_channels_channel_id'))
    )
    op.create_index('ix_youtube_channels_channel_id', 'youtube_channels', ['channel_id'], unique=True)
    op.create_table('assets',
    sa.Column('kind', sa.TEXT(), nullable=False),
    sa.Column('filename', sa.TEXT(), nullable=False),
    sa.Column('file_path', sa.TEXT(), nullable=False),
    sa.Column('file_size_bytes', sa.BIGINT(), nullable=False),
    sa.Column('mime_type', sa.TEXT(), nullable=True),
    sa.Column('hash_sha256', sa.TEXT(), nullable=False),
    sa.Column('width', sa.INTEGER(), nullable=True),
    sa.Column('height', sa.INTEGER(), nullable=True),
    sa.Column('duration_seconds', sa.FLOAT(), nullable=True),
    sa.Column('tags', drevalis.models._types.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('image', 'video', 'audio', 'other')", name=op.f('ck_assets_ck_assets_kind_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assets_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('hash_sha256', name=op.f('uq_assets_hash_sha256'))
    )
    op.create_index('ix_assets_created_at', 'assets', ['created_at'], unique=False)
    op.create_index('ix_assets_kind', 'assets', ['kind'], unique=False)
    op.create_index('ix_assets_tags_gin', 'assets', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('audiobooks',
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('voice_profile_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default='draft', nullable=False),
    sa.Column('output_format', sa.TEXT(), server_default='audio_only', nullable=False),
    sa.Column('cover_image_path', sa.TEXT(), nullable=True),
    sa.Column('chapters', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('voice_casting', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('music_enabled', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('music_mood', sa.TEXT(), nullable=True),
    sa.Column('music_volume_db', sa.NUMERIC(), server_default='-14.0', nullable=False),
    sa.Column('track_mix', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('settings_json', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('job_state', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('render_plan_json', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('speed', sa.NUMERIC(), server_default='1.0', nullable=False),
    sa.Column('pitch', sa.NUMERIC(), server_default='1.0', nullable=False),
    sa.Column('audio_path', sa.TEXT(), nullable=True),
    sa.Column('video_path', sa.TEXT(), nullable=True),
    sa.Column('mp3_path', sa.TEXT(), nullable=True),
    sa.Column('duration_seconds', sa.NUMERIC(), nullable=True),
    sa.Column('file_size_bytes', sa.BIGINT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('background_image_path', sa.TEXT(), nullable=True),
    sa.Column('video_orientation', sa.TEXT(), server_default='landscape', nullable=False),
    sa.Column('caption_style_preset', sa.TEXT(), nullable=True),
    sa.Column('image_generation_enabled', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('youtube_channel_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("output_format IN ('audio_only', 'audio_image', 'audio_video')", name=op.f('ck_audiobooks_ck_audiobooks_output_format')),
    sa.CheckConstraint("status IN ('draft', 'generating', 'done', 'failed')", name=op.f('ck_audiobooks_status_valid')),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], name=op.f('fk_audiobooks_voice_profile_id_voice_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['youtube_channel_id'], ['youtube_channels.id'], name=op.f('fk_audiobooks_youtube_channel_id_youtube_channels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audiobooks'))
    )
    op.create_index('ix_audiobooks_status', 'audiobooks', ['status'], unique=False)
    op.create_table('login_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email_attempted', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip', sa.TEXT(), nullable=False),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.Column('failure_reason', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_events'))
    )
    op.create_index('ix_login_events_ip_ts', 'login_events', ['ip', 'timestamp'], unique=False)
    op.create_index('ix_login_events_user_ts', 'login_events', ['user_id', 'timestamp'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index('ix_prt_user_used_expires', 'password_reset_tokens', ['user_id', 'used_at', 'expires_at'], unique=False)
    op.create_table('scheduled_posts',
    sa.Column('content_type', sa.TEXT(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.TEXT(), nullable=False),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('privacy', sa.TEXT(), server_default='private', nullable=False),
    sa.Column('status', sa.TEXT(), server_default='scheduled', nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('remote_id', sa.TEXT(), nullable=True),
    sa.Column('remote_url', sa.TEXT(), nullable=True),
    sa.Column('youtube_channel_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("content_type IN ('episode', 'audiobook')", name=op.f('ck_scheduled_posts_sched_content_type_valid')),
    sa.CheckConstraint("platform IN ('youtube', 'tiktok', 'instagram', 'x', 'facebook')", name=op.f('ck_scheduled_posts_sched_platform_valid')),
    sa.CheckConstraint("privacy IN ('public', 'unlisted', 'private')", name=op.f('ck_scheduled_posts_sched_privacy_valid')),
    sa.CheckConstraint("status IN ('scheduled', 'publishing', 'published', 'failed', 'cancelled')", name=op.f('ck_scheduled_posts_sched_status_valid')),
    sa.ForeignKeyConstraint(['youtube_channel_id'], ['youtube_channels.id'], name=op.f('fk_scheduled_posts_youtube_channel_id_youtube_channels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_posts'))
    )
    op.create_index('ix_scheduled_posts_scheduled_at', 'scheduled_posts', ['scheduled_at'], unique=False)
    op.create_index('ix_scheduled_posts_status', 'scheduled_posts', ['status'], unique=False)
    op.create_index('ix_scheduled_posts_status_scheduled_at', 'scheduled_posts', ['status', 'scheduled_at'], unique=False)
    op.create_index('ix_scheduled_posts_youtube_channel_id', 'scheduled_posts', ['youtube_channel_id'], unique=False)
    op.create_table('series',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('voice_profile_id', sa.Uuid(), nullable=True),
    sa.Column('comfyui_server_id', sa.Uuid(), nullable=True),
    sa.Column('comfyui_workflow_id', sa.Uuid(), nullable=True),
    sa.Column('llm_config_id', sa.Uuid(), nullable=True),
    sa.Column('script_prompt_template_id', sa.Uuid(), nullable=True),
    sa.Column('visual_prompt_template_id', sa.Uuid(), nullable=True),
    sa.Column('visual_style', sa.TEXT(), nullable=True),
    sa.Column('character_description', sa.TEXT(), nullable=True),
    sa.Column('target_duration_seconds', sa.INTEGER(), nullable=False),
    sa.Column('default_language', sa.TEXT(), server_default='en-US', nullable=False),
    sa.Column('caption_style', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('negative_prompt', sa.TEXT(), nullable=True),
    sa.Column('scene_mode', sa.String(), server_default=sa.text("'image'"), nullable=False),
    sa.Column('video_comfyui_workflow_id', sa.Uuid(), nullable=True),
    sa.Column('music_mood', sa.TEXT(), nullable=True),
    sa.Column('music_volume_db', sa.NUMERIC(), server_default=sa.text("'-14.0'"), nullable=False),
    sa.Column('music_enabled', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('content_format', sa.String(length=20), server_default=sa.text("'shorts'"), nullable=False),
    sa.Column('target_duration_minutes', sa.INTEGER(), nullable=True),
    sa.Column('chapter_enabled', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('scenes_per_chapter', sa.INTEGER(), server_default=sa.text('8'), nullable=False),
    sa.Column('transition_style', sa.String(length=50), nullable=True),
    sa.Column('transition_duration', sa.Float(), server_default=sa.text('(0.5)'), nullable=False),
    sa.Column('duration_match_strategy', sa.String(length=20), server_default=sa.text("'hold_frame'"), nullable=False),
    sa.Column('base_seed', sa.INTEGER(), nullable=True),
    sa.Column('intro_template', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('outro_template', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('visual_consistency_prompt', sa.TEXT(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=10), server_default=sa.text("'9:16'"), nullable=False),
    sa.Column('thumbnail_mode', sa.String(length=20), server_default=sa.text("'smart_frame'"), nullable=False),
    sa.Column('thumbnail_comfyui_workflow_id', sa.Uuid(), nullable=True),
    sa.Column('music_bpm', sa.INTEGER(), nullable=True),
    sa.Column('music_key', sa.String(length=20), nullable=True),
    sa.Column('audio_preset', sa.String(length=20), nullable=True),
    sa.Column('video_clip_duration', sa.INTEGER(), server_default=sa.text('5'), nullable=False),
    sa.Column('youtube_channel_id', sa.Uuid(), nullable=True),
    sa.Column('reference_asset_ids', sa.JSON(), nullable=True),
    sa.Column('character_lock', sa.JSON(), nullable=True),
    sa.Column('style_lock', sa.JSON(), nullable=True),
    sa.Column('tone_profile', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('target_duration_seconds IN (15, 30, 60)', name=op.f('ck_series_target_duration_valid')),
    sa.ForeignKeyConstraint(['comfyui_server_id'], ['comfyui_servers.id'], name=op.f('fk_series_comfyui_server_id_comfyui_servers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['comfyui_workflow_id'], ['comfyui_workflows.id'], name=op.f('fk_series_comfyui_workflow_id_comfyui_workflows'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['llm_config_id'], ['llm_configs.id'], name=op.f('fk_series_llm_config_id_llm_configs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['script_prompt_template_id'], ['prompt_templates.id'], name=op.f('fk_series_script_prompt_template_id_prompt_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thumbnail_comfyui_workflow_id'], ['comfyui_workflows.id'], name=op.f('fk_series_thumbnail_comfyui_workflow_id_comfyui_workflows'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_comfyui_workflow_id'], ['comfyui_workflows.id'], name=op.f('fk_series_video_comfyui_workflow_id_comfyui_workflows'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visual_prompt_template_id'], ['prompt_templates.id'], name=op.f('fk_series_visual_prompt_template_id_prompt_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], name=op.f('fk_series_voice_profile_id_voice_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['youtube_channel_id'], ['youtube_channels.id'], name=op.f('fk_series_youtube_channel_id_youtube_channels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series')),
    sa.UniqueConstraint('name', name=op.f('uq_series_name'))
    )
    op.create_index('ix_series_content_format', 'series', ['content_format'], unique=False)
    op.create_index('ix_series_youtube_channel_id', 'series', ['youtube_channel_id'], unique=False)
    op.create_table('video_templates',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('voice_profile_id', sa.Uuid(), nullable=True),
    sa.Column('visual_style', sa.TEXT(), nullable=True),
    sa.Column('scene_mode', sa.TEXT(), nullable=True),
    sa.Column('caption_style_preset', sa.TEXT(), nullable=True),
    sa.Column('music_enabled', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('music_mood', sa.TEXT(), nullable=True),
    sa.Column('music_volume_db', sa.FLOAT(), server_default=sa.text("'-14.0'"), nullable=False),
    sa.Column('audio_settings', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('target_duration_seconds', sa.INTEGER(), server_default=sa.text('(30)'), nullable=False),
    sa.Column('times_used', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], name=op.f('fk_video_templates_voice_profile_id_voice_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_templates'))
    )
    op.create_table('youtube_playlists',
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('youtube_playlist_id', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('privacy_status', sa.TEXT(), server_default=sa.text("'private'"), nullable=False),
    sa.Column('item_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("privacy_status IN ('public', 'unlisted', 'private')", name=op.f('ck_youtube_playlists_playlist_privacy_status_valid')),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], name=op.f('fk_youtube_playlists_channel_id_youtube_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_playlists'))
    )
    op.create_index('ix_youtube_playlists_channel_id', 'youtube_playlists', ['channel_id'], unique=False)
    op.create_index('ix_youtube_playlists_youtube_playlist_id', 'youtube_playlists', ['youtube_playlist_id'], unique=False)
    op.create_table('episodes',
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('topic', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default='draft', nullable=False),
    sa.Column('script', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('base_path', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('generation_log', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('metadata', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('override_voice_profile_id', sa.Uuid(), nullable=True),
    sa.Column('override_llm_config_id', sa.Uuid(), nullable=True),
    sa.Column('override_caption_style', sa.TEXT(), nullable=True),
    sa.Column('content_format', sa.String(length=20), server_default='shorts', nullable=False),
    sa.Column('chapters', drevalis.models._types.JSONB(), nullable=True),
    sa.Column('total_duration_seconds', sa.Float(), nullable=True),
    sa.Column('reference_asset_ids', sa.JSON(), nullable=True),
    sa.Column('video_ingest_source_asset_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'generating', 'review', 'editing', 'exported', 'failed')", name=op.f('ck_episodes_status_valid')),
    sa.ForeignKeyConstraint(['override_llm_config_id'], ['llm_configs.id'], name=op.f('fk_episodes_override_llm_config_id_llm_configs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['override_voice_profile_id'], ['voice_profiles.id'], name=op.f('fk_episodes_override_voice_profile_id_voice_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_episodes_series_id_series'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_ingest_source_asset_id'], ['assets.id'], name=op.f('fk_episodes_video_ingest_source_asset_id_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episodes'))
    )
    op.create_index('ix_episodes_created_at', 'episodes', ['created_at'], unique=False)
    op.create_index('ix_episodes_series_id_status', 'episodes', ['series_id', 'status'], unique=False)
    op.create_index('ix_episodes_status', 'episodes', ['status'], unique=False)
    op.create_table('youtube_audiobook_uploads',
    sa.Column('audiobook_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('youtube_video_id', sa.TEXT(), nullable=True),
    sa.Column('youtube_url', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('privacy_status', sa.TEXT(), server_default=sa.text("'private'"), nullable=False),
    sa.Column('upload_status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('playlist_id', sa.TEXT(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("privacy_status IN ('public', 'unlisted', 'private')", name=op.f('ck_youtube_audiobook_uploads_audiobook_privacy_status_valid')),
    sa.CheckConstraint("upload_status IN ('pending', 'uploading', 'done', 'failed')", name=op.f('ck_youtube_audiobook_uploads_audiobook_upload_status_valid')),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], name=op.f('fk_youtube_audiobook_uploads_audiobook_id_audiobooks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], name=op.f('fk_youtube_audiobook_uploads_channel_id_youtube_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_audiobook_uploads'))
    )
    op.create_index('ix_youtube_audiobook_uploads_audiobook_id', 'youtube_audiobook_uploads', ['audiobook_id'], unique=False)
    op.create_index('ix_youtube_audiobook_uploads_channel_id', 'youtube_audiobook_uploads', ['channel_id'], unique=False)
    op.create_table('ab_tests',
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('episode_a_id', sa.Uuid(), nullable=False),
    sa.Column('episode_b_id', sa.Uuid(), nullable=False),
    sa.Column('variant_label', sa.TEXT(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('winner_episode_id', sa.Uuid(), nullable=True),
    sa.Column('comparison_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('episode_a_id <> episode_b_id', name=op.f('ck_ab_tests_distinct_episodes')),
    sa.ForeignKeyConstraint(['episode_a_id'], ['episodes.id'], name=op.f('fk_ab_tests_episode_a_id_episodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_b_id'], ['episodes.id'], name=op.f('fk_ab_tests_episode_b_id_episodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_ab_tests_series_id_series'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_episode_id'], ['episodes.id'], name=op.f('fk_ab_tests_winner_episode_id_episodes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ab_tests'))
    )
    op.create_index('ix_ab_tests_series_id_q', 'ab_tests', ['series_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('step', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default='queued', nullable=False),
    sa.Column('progress_pct', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('worker_id', sa.TEXT(), nullable=True),
    sa.Column('chapter_number', sa.INTEGER(), nullable=True),
    sa.Column('scene_number', sa.INTEGER(), nullable=True),
    sa.Column('total_items', sa.INTEGER(), nullable=True),
    sa.Column('completed_items', sa.INTEGER(), nullable=True),
    sa.Column('tokens_prompt', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('tokens_completion', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name=op.f('ck_generation_jobs_status_valid')),
    sa.CheckConstraint("step IN ('script', 'voice', 'scenes', 'captions', 'assembly', 'thumbnail')", name=op.f('ck_generation_jobs_step_valid')),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_generation_jobs_episode_id_episodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_jobs'))
    )
    op.create_index('ix_generation_jobs_episode_id', 'generation_jobs', ['episode_id'], unique=False)
    op.create_index('ix_generation_jobs_episode_id_step', 'generation_jobs', ['episode_id', 'step'], unique=False)
    op.create_index('ix_generation_jobs_status', 'generation_jobs', ['status'], unique=False)
    op.create_table('social_uploads',
    sa.Column('platform_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=True),
    sa.Column('content_type', sa.TEXT(), server_default=sa.text("'episode'"), nullable=False),
    sa.Column('platform_content_id', sa.TEXT(), nullable=True),
    sa.Column('platform_url', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('hashtags', sa.TEXT(), nullable=True),
    sa.Column('upload_status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('views', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('likes', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('comments', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('shares', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("content_type IN ('episode', 'audiobook')", name=op.f('ck_social_uploads_social_content_type_valid')),
    sa.CheckConstraint("upload_status IN ('pending', 'uploading', 'done', 'failed')", name=op.f('ck_social_uploads_social_upload_status_valid')),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_social_uploads_episode_id_episodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['social_platforms.id'], name=op.f('fk_social_uploads_platform_id_social_platforms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_uploads'))
    )
    op.create_index('ix_social_uploads_content_type', 'social_uploads', ['content_type'], unique=False)
    op.create_index('ix_social_uploads_episode_id', 'social_uploads', ['episode_id'], unique=False)
    op.create_index('ix_social_uploads_platform_id', 'social_uploads', ['platform_id'], unique=False)
    op.create_table('video_edit_sessions',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('timeline', drevalis.models._types.JSONB(), nullable=False),
    sa.Column('last_render_job_id', sa.Uuid(), nullable=True),
    sa.Column('last_rendered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_video_edit_sessions_episode_id_episodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_edit_sessions')),
    sa.UniqueConstraint('episode_id', name=op.f('uq_video_edit_sessions_episode_id'))
    )
    op.create_table('video_ingest_jobs',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default='queued', nullable=False),
    sa.Column('progress_pct', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('stage', sa.TEXT(), nullable=True),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.Column('candidate_clips', sa.JSON(), nullable=True),
    sa.Column('selected_clip_index', sa.INTEGER(), nullable=True),
    sa.Column('resulting_episode_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name=op.f('ck_video_ingest_jobs_ck_video_ingest_status_valid')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_video_ingest_jobs_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resulting_episode_id'], ['episodes.id'], name=op.f('fk_video_ingest_jobs_resulting_episode_id_episodes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_ingest_jobs'))
    )
    op.create_index('ix_video_ingest_status', 'video_ingest_jobs', ['status'], unique=False)
    op.create_table('youtube_uploads',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('youtube_video_id', sa.TEXT(), nullable=True),
    sa.Column('youtube_url', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('privacy_status', sa.TEXT(), server_default=sa.text("'private'"), nullable=False),
    sa.Column('upload_status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("privacy_status IN ('public', 'unlisted', 'private')", name=op.f('ck_youtube_uploads_privacy_status_valid')),
    sa.CheckConstraint("upload_status IN ('pending', 'uploading', 'done', 'failed')", name=op.f('ck_youtube_uploads_upload_status_valid')),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], name=op.f('fk_youtube_uploads_channel_id_youtube_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_youtube_uploads_episode_id_episodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_uploads'))
    )
    op.create_index('ix_youtube_uploads_channel_id', 'youtube_uploads', ['channel_id'], unique=False)
    op.create_index('ix_youtube_uploads_episode_id', 'youtube_uploads', ['episode_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.TEXT(), nullable=False),
    sa.Column('file_path', sa.TEXT(), nullable=False),
    sa.Column('file_size_bytes', sa.BIGINT(), nullable=True),
    sa.Column('duration_seconds', sa.NUMERIC(), nullable=True),
    sa.Column('scene_number', sa.INTEGER(), nullable=True),
    sa.Column('generation_job_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("asset_type IN ('voiceover', 'scene', 'scene_image', 'scene_video', 'caption', 'video', 'video_proxy', 'thumbnail', 'temp')", name=op.f('ck_media_assets_asset_type_valid')),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_media_assets_episode_id_episodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], name=op.f('fk_media_assets_generation_job_id_generation_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    op.create_index('ix_media_assets_episode_id', 'media_assets', ['episode_id'], unique=False)
    op.create_index('ix_media_assets_episode_id_asset_type', 'media_assets', ['episode_id', 'asset_type'], unique=False)
    op.create_index('ix_media_assets_episode_id_scene_number', 'media_assets', ['episode_id', 'scene_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_assets_episode_id_scene_number', table_name='media_assets')
    op.drop_index('ix_media_assets_episode_id_asset_type', table_name='media_assets')
    op.drop_index('ix_media_assets_episode_id', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('ix_youtube_uploads_episode_id', table_name='youtube_uploads')
    op.drop_index('ix_youtube_uploads_channel_id', table_name='youtube_uploads')
    op.drop_table('youtube_uploads')
    op.drop_index('ix_video_ingest_status', table_name='video_ingest_jobs')
    op.drop_table('video_ingest_jobs')
    op.drop_table('video_edit_sessions')
    op.drop_index('ix_social_uploads_platform_id', table_name='social_uploads')
    op.drop_index('ix_social_uploads_episode_id', table_name='social_uploads')
    op.drop_index('ix_social_uploads_content_type', table_name='social_uploads')
    op.drop_table('social_uploads')
    op.drop_index('ix_generation_jobs_status', table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_episode_id_step', table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_episode_id', table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index('ix_ab_tests_series_id_q', table_name='ab_tests')
    op.drop_table('ab_tests')
    op.drop_index('ix_youtube_audiobook_uploads_channel_id', table_name='youtube_audiobook_uploads')
    op.drop_index('ix_youtube_audiobook_uploads_audiobook_id', table_name='youtube_audiobook_uploads')
    op.drop_table('youtube_audiobook_uploads')
    op.drop_index('ix_episodes_status', table_name='episodes')
    op.drop_index('ix_episodes_series_id_status', table_name='episodes')
    op.drop_index('ix_episodes_created_at', table_name='episodes')
    op.drop_table('episodes')
    op.drop_index('ix_youtube_playlists_youtube_playlist_id', table_name='youtube_playlists')
    op.drop_index('ix_youtube_playlists_channel_id', table_name='youtube_playlists')
    op.drop_table('youtube_playlists')
    op.drop_table('video_templates')
    op.drop_index('ix_series_youtube_channel_id', table_name='series')
    op.drop_index('ix_series_content_format', table_name='series')
    op.drop_table('series')
    op.drop_index('ix_scheduled_posts_youtube_channel_id', table_name='scheduled_posts')
    op.drop_index('ix_scheduled_posts_status_scheduled_at', table_name='scheduled_posts')
    op.drop_index('ix_scheduled_posts_status', table_name='scheduled_posts')
    op.drop_index('ix_scheduled_posts_scheduled_at', table_name='scheduled_posts')
    op.drop_table('scheduled_posts')
    op.drop_index('ix_prt_user_used_expires', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_login_events_user_ts', table_name='login_events')
    op.drop_index('ix_login_events_ip_ts', table_name='login_events')
    op.drop_table('login_events')
    op.drop_index('ix_audiobooks_status', table_name='audiobooks')
    op.drop_table('audiobooks')
    op.drop_index('ix_assets_tags_gin', table_name='assets', postgresql_using='gin')
    op.drop_index('ix_assets_kind', table_name='assets')
    op.drop_index('ix_assets_created_at', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_youtube_channels_channel_id', table_name='youtube_channels')
    op.drop_table('youtube_channels')
    op.drop_table('voice_profiles')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_social_platforms_platform_account', table_name='social_platforms')
    op.drop_index('ix_social_platforms_platform', table_name='social_platforms')
    op.drop_table('social_platforms')
    op.drop_table('prompt_templates')
    op.drop_table('llm_configs')
    op.drop_table('license_state')
    op.drop_table('comfyui_workflows')
    op.drop_table('comfyui_servers')
    op.drop_table('character_packs')
    op.drop_table('api_key_store')
    # ### end Alembic commands ###
